/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.graficaSwing;

import java.awt.Color;

/**
 *
 * @author adolfojr
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form loginUsuario
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        imagenLateral = new javax.swing.JLabel();
        iniciar_sesion_txt = new javax.swing.JLabel();
        usuario_txt = new javax.swing.JLabel();
        ingresar_usuario = new javax.swing.JTextField();
        separador_1 = new javax.swing.JSeparator();
        contraseña_txt = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        separador_2 = new javax.swing.JSeparator();
        ingresar = new javax.swing.JPanel();
        ingresar_txt = new javax.swing.JLabel();
        barra_superior = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(51, 153, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenLateral.setIcon(new javax.swing.ImageIcon("/Users/adolfojr/Desktop/img_proyecto/busq-trabajo.jpeg")); // NOI18N
        imagenLateral.setText("jLabel1");
        background.add(imagenLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 310, 570));

        iniciar_sesion_txt.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        iniciar_sesion_txt.setText("INICIAR SESIÓN");
        background.add(iniciar_sesion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        usuario_txt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        usuario_txt.setText("USUARIO");
        background.add(usuario_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        ingresar_usuario.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        ingresar_usuario.setForeground(new java.awt.Color(204, 204, 204));
        ingresar_usuario.setText("Ingrese su nombre de usuario");
        ingresar_usuario.setBorder(null);
        ingresar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_usuarioMousePressed(evt);
            }
        });
        background.add(ingresar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 350, 30));

        separador_1.setBackground(new java.awt.Color(0, 0, 0));
        separador_1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(separador_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 370, 30));

        contraseña_txt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        contraseña_txt.setText("CONTRASEÑA");
        background.add(contraseña_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        password.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("********");
        password.setBorder(null);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordMousePressed(evt);
            }
        });
        background.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 370, 30));

        separador_2.setBackground(new java.awt.Color(0, 0, 0));
        separador_2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(separador_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 370, 30));

        ingresar.setBackground(new java.awt.Color(153, 204, 255));

        ingresar_txt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        ingresar_txt.setForeground(new java.awt.Color(255, 255, 255));
        ingresar_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresar_txt.setText("INGRESAR");
        ingresar_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresar_txtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresar_txtMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout ingresarLayout = new javax.swing.GroupLayout(ingresar);
        ingresar.setLayout(ingresarLayout);
        ingresarLayout.setHorizontalGroup(
            ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresar_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        ingresarLayout.setVerticalGroup(
            ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresar_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 160, 50));

        barra_superior.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout barra_superiorLayout = new javax.swing.GroupLayout(barra_superior);
        barra_superior.setLayout(barra_superiorLayout);
        barra_superiorLayout.setHorizontalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        barra_superiorLayout.setVerticalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        background.add(barra_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresar_txtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_txtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_txtMouseEntered

    private void ingresar_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_usuarioMousePressed
        
        if (ingresar_usuario.getText().equals("Ingrese su nombre de usuario")){
            ingresar_usuario.setText("");
            ingresar_usuario.setForeground(Color.black);
        }
        if(String.valueOf(password.getPassword()).isEmpty()){
            password.setText("********");
            password.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingresar_usuarioMousePressed

    private void passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMousePressed
        
        if(String.valueOf(password.getPassword()).equals("********")){
            password.setText("");
            password.setForeground(Color.black);
        }
        if(ingresar_usuario.getText().isEmpty()){
            ingresar_usuario.setText("Ingrese su nombre de usuario");
            ingresar_usuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passwordMousePressed

    private void ingresar_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_txtMouseClicked
        // TODO add your handling code here:
        String user,pass;
        String adminUser = "admin";
        String adminPass = "admin";
        
        user = ingresar_usuario.getText().trim();
        pass = ingresar_usuario.getText().trim();
        
        if(user.equals(adminUser) && pass.equals(adminPass)){
            adminWindow window1 = new adminWindow();
            window1.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_ingresar_txtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel barra_superior;
    private javax.swing.JLabel contraseña_txt;
    private javax.swing.JLabel imagenLateral;
    private javax.swing.JPanel ingresar;
    private javax.swing.JLabel ingresar_txt;
    private javax.swing.JTextField ingresar_usuario;
    private javax.swing.JLabel iniciar_sesion_txt;
    private javax.swing.JPasswordField password;
    private javax.swing.JSeparator separador_1;
    private javax.swing.JSeparator separador_2;
    private javax.swing.JLabel usuario_txt;
    // End of variables declaration//GEN-END:variables
}
