/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.graficaSwing;

/**
 *
 * @author adolfojr
 */
public class paginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form paginaPrincipal
     */
    public paginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        barraSuperior = new javax.swing.JPanel();
        iniciarSesion = new javax.swing.JPanel();
        iniciarSesionLabel = new javax.swing.JLabel();
        registrarse = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscarEmpleo = new javax.swing.JPanel();
        empleoLabel = new javax.swing.JLabel();
        imagenLateral = new javax.swing.JLabel();
        cargoField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraSuperior.setBackground(new java.awt.Color(102, 102, 255));

        iniciarSesion.setBackground(new java.awt.Color(255, 153, 51));

        iniciarSesionLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        iniciarSesionLabel.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciarSesionLabel.setText("INICIAR SESIÓN");
        iniciarSesionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout iniciarSesionLayout = new javax.swing.GroupLayout(iniciarSesion);
        iniciarSesion.setLayout(iniciarSesionLayout);
        iniciarSesionLayout.setHorizontalGroup(
            iniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciarSesionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );
        iniciarSesionLayout.setVerticalGroup(
            iniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciarSesionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        registrarse.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout registrarseLayout = new javax.swing.GroupLayout(registrarse);
        registrarse.setLayout(registrarseLayout);
        registrarseLayout.setHorizontalGroup(
            registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );
        registrarseLayout.setVerticalGroup(
            registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraSuperiorLayout = new javax.swing.GroupLayout(barraSuperior);
        barraSuperior.setLayout(barraSuperiorLayout);
        barraSuperiorLayout.setHorizontalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraSuperiorLayout.createSequentialGroup()
                .addContainerGap(520, Short.MAX_VALUE)
                .addComponent(iniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        barraSuperiorLayout.setVerticalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelPrincipal.add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 80));

        buscarEmpleo.setBackground(new java.awt.Color(255, 102, 51));

        empleoLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        empleoLabel.setForeground(new java.awt.Color(255, 255, 255));
        empleoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empleoLabel.setText("BUSCAR EMPLEO");
        empleoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout buscarEmpleoLayout = new javax.swing.GroupLayout(buscarEmpleo);
        buscarEmpleo.setLayout(buscarEmpleoLayout);
        buscarEmpleoLayout.setHorizontalGroup(
            buscarEmpleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarEmpleoLayout.createSequentialGroup()
                .addComponent(empleoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        buscarEmpleoLayout.setVerticalGroup(
            buscarEmpleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empleoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelPrincipal.add(buscarEmpleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 290, 50));

        imagenLateral.setIcon(new javax.swing.ImageIcon("/Users/adolfojr/Desktop/img_proyecto/El-futuro-del-trabajo-en-America-Latina-e1551189693581-1.png")); // NOI18N
        imagenLateral.setText("jLabel2");
        panelPrincipal.add(imagenLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 400, 470));

        cargoField.setBackground(new java.awt.Color(204, 204, 204));
        cargoField.setText("Indique nombre del cargo que desea");
        cargoField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cargoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cargoFieldMousePressed(evt);
            }
        });
        panelPrincipal.add(cargoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 250, 380, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargoFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargoFieldMousePressed
        
        cargoField.setText("");
    }//GEN-LAST:event_cargoFieldMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JPanel buscarEmpleo;
    private javax.swing.JTextField cargoField;
    private javax.swing.JLabel empleoLabel;
    private javax.swing.JLabel imagenLateral;
    private javax.swing.JPanel iniciarSesion;
    private javax.swing.JLabel iniciarSesionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel registrarse;
    // End of variables declaration//GEN-END:variables
}
